# Generated by Django 4.2.2 on 2023-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='serial_no',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='serial_no',
            new_name='sno',
        ),
    ]
