# Generated by Django 4.2.2 on 2023-07-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(default=int, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='sno',
            field=models.AutoField(default=int, primary_key=True, serialize=False),
        ),
    ]
