# Generated by Django 4.2.2 on 2023-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcomment_sno_alter_post_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
