# Generated by Django 4.2.2 on 2023-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_sno_blogcomment_lno_rename_sno_post_lno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='lno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='lno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
