# Generated by Django 4.2.2 on 2023-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='serial_no',
            new_name='sno',
        ),
    ]
