# Generated by Django 4.2.2 on 2023-07-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contact_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sno',
            new_name='lno',
        ),
    ]
